### ISSUE TITLE
@font-face: Same name with different styles

### ISSUE THREAD

**Issue by femesq** [styletron/styletron#270]
Looking at the sources and the docs, I couldn't be sure if using `@font-face` with different files for each `font-style`'s on the same `font-family` would work:

```css
@font-face {
  font-family: 'Montserrat';
  src: url('#{$media-path-fonts}/Montserrat-Bold.eot');
  src: url('#{$media-path-fonts}/Montserrat-Bold.woff2') format('woff2'),
  url('#{$media-path-fonts}/Montserrat-Bold.woff') format('woff'),
  url('#{$media-path-fonts}/Montserrat-Bold.ttf') format('truetype');
  font-weight: 900;
  font-style: normal;
}

@font-face {
  font-family: 'Montserrat';
  src: url('#{$media-path-fonts}/Montserrat-BoldItalic.eot');
  src: url('#{$media-path-fonts}/Montserrat-BoldItalic.woff2') format('woff2'),
  url('#{$media-path-fonts}/Montserrat-BoldItalic.woff') format('woff'),
  url('#{$media-path-fonts}/Montserrat-BoldItalic.ttf') format('truetype');
  font-weight: 900;
  font-style: italic;
}

```

... Neither if it would support [deep Browser support](https://css-tricks.com/snippets/css/using-font-face/#article-header-id-0) which needs two `src` keys.

Anyone tried this?

Somewhat related: [#236](https://github.com/styletron/styletron/issues/236)
