### ISSUE TITLE
allow injection of css rules to cover cases that styletron cannot do

### ISSUE THREAD

**Issue by rook2pawn** [styletron/styletron#348]
**background:** want to 
```css
.parent:hover .child {
   opacity: 1
}
```

but the alternatives are really bad, to add and remove listeners with useHover is like we're coding in 2002. the computation costs are literally what css2 selectors solved.

Either allow injection of rules or dynamic local selectors like sheetify.
