### ISSUE TITLE
How to mirror style in RTL language?

### ISSUE THREAD

**Issue by behnammodi** [styletron/styletron#389]
Hi there, i want to mirror style in RTL langugage for example:

`padding-left: 5px` change to `padding-right:5px` in RTL

How can I do?

**Comment by behnammodi** [comment]
If it's not possible now I can work on it

**Comment by tajo** [comment]
Instead of `padding-left` you should use `padding-inline-end`. That's imo better approach than trying to programmatically switch styles. More info:

https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/RTL_Guidelines

**Comment by behnammodi** [comment]
@tajo Thank you man, but `padding-inline-start` is not good support by browsers and it does not work on IE and old browser

Please see this link: https://caniuse.com/mdn-css_properties_padding-inline-start

Also sometimes we need to convert `left` to `right` ex:

```css
.badge{
  position: absolute;
  left: 5px;
  top: 5px:
  ....
}
```

how convert to:

```css
.badge{
  position: absolute;
  right: 5px;
  top: 5px:
  ....
}
```

and also sometimes you need to mirror value instead of attribute ex:

`transform: translateX(100%)` so you need to convert to `transform: translateX(-100%)`
