### ISSUE TITLE
Idea: Also support shorthand properties 

### ISSUE THREAD

**Issue by Janther** [styletron/styletron#89]
Since this tool is all about atomic css declarations, how about transforming:

```CSS
padding: 25px 50px 75px 100px;
```

into:

```CSS
.a { padding-top: 25px; }
.b { padding-right: 50px; }
.c { padding-bottom: 75px; }
.d { padding-left: 100px; }
```

the same could be applied to other shorthand properties.
